import * as cdk from 'aws-cdk-lib';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

// Only JWT secret here — DB credentials are generated by RDS in rds-stack.ts
// to avoid a cyclic cross-stack dependency (SecretsStack <-> RdsStack)
export class SecretsStack extends cdk.Stack {
  public readonly jwtSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.jwtSecret = new secretsmanager.Secret(this, 'JwtSecret', {
      secretName: 'incidents/jwt-secret',
      description: 'JWT signing secret for Incident & Status Portal',
      generateSecretString: {
        passwordLength: 64,
        excludePunctuation: false,
        includeSpace: false,
      },
    });

    new cdk.CfnOutput(this, 'JwtSecretArn', {
      value: this.jwtSecret.secretArn,
      exportName: 'IncidentsJwtSecretArn',
    });
  }
}
